# Generated by Django 3.2.6 on 2021-08-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_time', models.CharField(max_length=20)),
                ('news_text', models.CharField(max_length=20)),
                ('news_inform', models.CharField(max_length=20)),
            ],
        ),
    ]
